# Generated by Django 3.2.4 on 2021-10-08 06:53

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eshop_product', '0004_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 8, 6, 53, 19, 347849, tzinfo=utc), verbose_name='تاریخ انقضا محصول'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.BooleanField(default=False, verbose_name='پیشنهاد امروز'),
        ),
        migrations.AddField(
            model_name='product',
            name='percent',
            field=models.IntegerField(default=0, verbose_name='درصد تخفیف'),
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='امتیاز')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='eshop_product.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'امتیاز ستاره\u200cای',
                'verbose_name_plural': 'امتیازهای ستاره\u200cای',
            },
        ),
    ]
