# Generated by Django 3.1.6 on 2021-02-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20210207_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='percent',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='درصد تخفیف'),
        ),
    ]
