# Generated by Django 3.1.6 on 2021-02-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20210207_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='offer',
            field=models.BooleanField(default=False, verbose_name='پیشنهاد ویژه'),
        ),
    ]
