# Generated by Django 3.0.7 on 2021-02-10 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_book_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='photo',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='name',
        ),
    ]
