# Generated by Django 3.2.4 on 2021-10-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_account', '0008_auto_20210618_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='title',
            field=models.CharField(blank=True, max_length=60, verbose_name='عنوان آدرس'),
        ),
    ]
