# Generated by Django 3.2.4 on 2021-10-07 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_category', '0004_alter_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='svg',
            field=models.FileField(default=1, upload_to='cat_images', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg'])], verbose_name='تصویر دسته\u200cبندی'),
            preserve_default=False,
        ),
    ]
