# Generated by Django 3.1.6 on 2021-02-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20210212_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_price',
            field=models.IntegerField(default=0, verbose_name='مبلغ پرداخت شده'),
        ),
    ]
