# Generated by Django 3.2.4 on 2021-10-20 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_order', '0007_auto_20210618_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='postway',
            name='duration',
            field=models.CharField(default=django.utils.timezone.now, max_length=60, verbose_name='مدت زمان ارسال'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postway',
            name='way',
            field=models.CharField(max_length=60, verbose_name='عنوان روش ارسال'),
        ),
    ]
