# Generated by Django 3.2.4 on 2021-10-20 18:09

from django.db import migrations, models
import eshop_order.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_order', '0008_auto_20211020_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='postway',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=eshop_order.models.upload_image_path, verbose_name='تصویر'),
        ),
    ]
