# Generated by Django 3.2.4 on 2021-10-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_order', '0009_postway_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postway',
            name='duration',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='مدت زمان ارسال'),
        ),
    ]
