# Generated by Django 3.2.4 on 2021-10-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_order', '0010_alter_postway_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postway',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='هزینه ارسال'),
        ),
    ]
