# Generated by Django 3.2.4 on 2021-11-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_order', '0011_alter_postway_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.CharField(blank=True, max_length=50, verbose_name='کد تخفیف'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_takhfif',
            field=models.IntegerField(blank=True, default=0, verbose_name='کسر مبلغ حاصل از کد تخفیف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total_products',
            field=models.IntegerField(blank=True, default=0, verbose_name='مبلغ کل محصولات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total_products_takhfif',
            field=models.IntegerField(blank=True, default=0, verbose_name='مبلغ کل محصولات بعد از کد تخفیف'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.IntegerField(blank=True, verbose_name='جمع تعداد کل سفارشات'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.IntegerField(blank=True, verbose_name='مبلغ قابل پرداخت'),
        ),
    ]
