# Generated by Django 3.2.4 on 2022-02-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_order', '0012_auto_20211106_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کد تخفیف'),
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon_takhfif',
            field=models.IntegerField(blank=True, null=True, verbose_name='کسر مبلغ حاصل از کد تخفیف'),
        ),
    ]
